services:
  postgres:
    image: postgres
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - C:\Users\Mirko Alarcon\Documents\UCB\I-2023\ArqSoftware\APICambioMoneda\Mio\dckCompose:/var/lib/postgresql/data
  currency-converter:
    image: demo:2.0.0
    restart: always
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      URL: ${POSTGRES_URL}
      USERNAME: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - C:\Users\Mirko Alarcon\Documents\UCB\I-2023\ArqSoftware\APICambioMoneda\Mio\dckComposeCurrency:/Users/Mirko Alarcon/Documents/UCB/I-2023/ArqSoftware/APICambioMoneda/Mio/logs
    depends_on:
      - postgres