services:
  postgres:
    image: postgres
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /Users/Mirko Alarcon/Documents/UCB/I-2023/ArqSoftware/APICambioMoneda/Mio/dckCompose:/var/lib/postgresql/data
    networks:
        - mrk-network
  currency-converter:
    image: demo:3.5.1
    restart: always
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      URL: ${POSTGRES_URL}
      USER_NAME: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /Users/Mirko Alarcon/Documents/UCB/I-2023/ArqSoftware/APICambioMoneda/Mio/dckComposeCurrency:/Users/Mirko Alarcon/Documents/UCB/I-2023/ArqSoftware/APICambioMoneda/Mio/logs
    depends_on:
      - postgres
    networks:
        - mrk-network
  angular:
    image: angular-software:3.5.1
    ports:
      - "4200:80"
    volumes:
      - /Users/Mirko Alarcon/Documents/UCB/I-2023/ArqSoftware/APICambioMoneda/Mio/Front/software/nginx.conf:/etc/nginx/nginx.conf
    networks:
        - mrk-network

networks:
  mrk-network:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: 172.1.0.0/16
              gateway: 172.1.0.1